@startuml　オブジェクト図

object 商品 {
  商品番号: int
  商品名: string
  価格: int
}

object ユーザー {
}

object 購入リスト {
  商品一覧: List<商品>
  合計金額: int
}

object 券売機 {
}

object 支払い {
  金額: int
  おつり: int
}

ユーザー "1" -l-> "*" 商品 : 選択
ユーザー "1" --> "1" 購入リスト : 追加
購入リスト -l-* 商品 : 含む
券売機 "1" --> 購入リスト : 処理
券売機 "1" --> 支払い : 処理
支払い -r-> 購入リスト : 確認
支払い --> 購入リスト : 成功
支払い --> 購入リスト : 失敗
支払い --> 購入リスト : おつり計算

@enduml