@startwbs 券売機WBS
title 券売機WBS

* 券売機
** 管理画面
*** 売り上げのリセット
**** 商品の価格変更
***** 管理画面の終了機能
** シミュレータ
*** 商品番号の受付
**** 繰り返し入力の受付
***** 意図しない値が入力されたとき
****** 特定の文字が入力されたときに一覧合計表示
******* 金額の入力を受け付ける
******** 入力した金額が意図しない値の場合
********* おつり返却
** 設計図
*** WBS
*** 依存関係図
*** クラス図
*** シーケンス図
*** ドメインモデル図
*** ユースケース図
*** オブジェクト図
*** アクティビティ図

@endwbs